package util

import (
	"os"
	"path/filepath"
)

const (
	// DefaultFileMode is the default file mode for files generated by
	// Dragonboat.
	DefaultFileMode    = 0640
	defaultDirFileMode = 0750
)

// Exist returns whether the specified filesystem entry exists.
func Exist(name string) (bool, error) {
	_, err := os.Stat(name)
	if err != nil && os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	return true, nil
}

// Mkdir creates the specified dir.
func Mkdir(dir string) error {
	if err := os.Mkdir(dir, defaultDirFileMode); err != nil {
		return err
	}
	return SyncDir(filepath.Dir(dir))
}

// SyncDir calls fsync on the specified directory.
func SyncDir(dir string) (err error) {
	fileInfo, err := os.Stat(dir)
	if err != nil {
		return err
	}
	if !fileInfo.IsDir() {
		panic("not a dir")
	}
	df, err := os.Open(filepath.Clean(dir))
	if err != nil {
		return err
	}
	defer func() {
		if cerr := df.Close(); err == nil {
			err = cerr
		}
	}()
	return df.Sync()
}

// MkdirAll creates the specified dir along with any necessary parents.
func MkdirAll(dir string) error {
	exist, err := Exist(dir)
	if err != nil {
		return err
	}
	if exist {
		return nil
	}
	parent := filepath.Dir(dir)
	exist, err = Exist(parent)
	if err != nil {
		return err
	}
	if !exist {
		if err := MkdirAll(parent); err != nil {
			return err
		}
	}
	return Mkdir(dir)
}
